// Generated by https://quicktype.io

import { AxiosError } from 'axios'
import tesloApi from '../api'

export interface LoginResp {
  id: string
  email: string
  fullName: string
  isActive: boolean
  roles: string[]
  token: string
}

export class AuthService {
  static login = async (
    email: string,
    password: string
  ): Promise<LoginResp> => {
    try {
      const { data } = await tesloApi.post<LoginResp>('/auth/login', {
        email,
        password,
      })

      return data
    } catch (error) {
      if (error instanceof AxiosError) {
        console.log(error.response?.data)
        throw new Error(error.response?.data.message)
      }
      throw new Error('Something went wrong')
    }
  }

  static checkStatus = async (): Promise<LoginResp> => {
    try {
      const { data } = await tesloApi.get<LoginResp>('/auth/check-status')

      return data
    } catch (error) {
      throw new Error('Unauthorized')
    }
  }
}
